### ISSUE TITLE
phonegap command can't find recipes (not copied on install)

### ISSUE THREAD

**Issue by pamelafox** [brianleroux/Cordova#7]
When I run the phonegap command, I get:
 No such file or directory:  /Library/Python/2.6/site-packages/cordova-0.1.0-py2.6.egg/recipes

When I look there, the recipes folder hasn't been copied there.
I'm not familiar with setup.py files, but from what I can tell, it finds out what packages to copy from this automatic setup_packages function, and that doesn't find recipe folders as they don't have **init**.py in them. I started adding that to them but that seemed the wrong way to solve this. Is there a modification to setup.py that will get the recipes copied over?
Or am I going about this incorrectly?

Thanks!

**Comment by brianleroux** [comment]
Hey Pamela --- the python installer stuff isn't really there yet. Just add the path to Cordova to your PATH in your bashrc or bash_profile. (This is mine: export PATH=$PATH:~/Repo/cordova)

**Comment by pamelafox** [comment]
I did that, but it still had issues. I'll wait until python installer stuff is more built out, build.phonegap.com works well enough for me for now. Feel free to close.

**Comment by sylvinus** [comment]
Did 

sudo cp -R ../Cordova/recipes /Library/Python/2.6/site-packages/cordova-0.1.0-py2.6.egg/
sudo cp -R ../Cordova/generate-template /Library/Python/2.6/site-packages/cordova-0.1.0-py2.6.egg/

to make it work

**Comment by brandon-rhodes** [comment]
I see what might be three separate issues with data files as I glance around a fresh checkout of the Cordova repository.
1. There seem to be two slightly different copies of the `generate-templates/` directory in the project: one sitting at the top level, and another beneath the `cordova/` package directory. Running “diff -r” on them shows that they have diverged slightly, but appear to have once been copies of the same data. The code in `create.py` that tries, and fails, to run when I type `phonegap create MyProject --www vanilla` appears to be looking for the outermost “generate-templates” directory, not the one that actually lives inside of the `cordova/` package, per the line that sets `root_path` to `../..` two levels above where that module itself sits.
2. Neither the top-level `recipes` nor the `generate-template` directory is listed as a directory that should get copied over into the Python by the `setup.py` file; only the second `generate-template` directory, the one that `create.py` ignores that is inside the `cordova` package itself, gets copied, but none of its actual data files makes it across — only `__init__.py`. It looks like work needs to be done on `setup.py` (and, if you ever wanted to distribute this on PyPI, a `MANIFEST.in` would be needed as well).
3. Finally, even if you could get the top-level `recipes` and `generate-template` directories to install, you would run into a problem of politeness: generally, Python packages should try to install such that all of their data files live somewhere inside of the package, instead of sitting outside of the package at the top level of the Python `site-packages` directory. Why? Because common names like `recipes` might conflict with some other Python package or project that someone tries to install; only by putting `recipes` inside of `cordova/` would you guarantee that you would not overwrite files belonging to another Python package.

I would be very happy to fork Cordova and fix all of these issues for you — since I have a bit of practice doing Python packaging ­— but I am stymied by the presence of two separate `generate-template` directories. Could you help me figure out which one to keep and which to throw away — or whether they are both useful in some way that I am missing? Once I know that, getting the packaging to work correctly will be very simple and issues #7 and #15 could be fixed by the end of the evening.

Thanks for providing Cordova, and I look forward to having it install successfully! :)

**Comment by brandon-rhodes** [comment]
Oh: and, for people wanting Cordova to work Right Now using standard Python tools, you should check out the project from github and then run:

`pip install -e Cordova`

on the resulting repository directory. This will tell Python to run the package right out of its repository, where the afore-mentioned directories are already present, instead of trying to run `setup.py` and only copying some of the files it needs.

**Comment by Kotrotsos** [comment]
Indeed copy /recipes and /generate-template over to site-packages folder for this to work. In my case it was

cp -R recipes /Users/me/.virtualenvs/mypy/lib/python2.7/site-packages/cordova-0.1.0-py2.7.egg
cp -R generate-template /Users/me/.virtualenvs/mypy/lib/python2.7/site-packages/cordova-0.1.0-py2.7.egg

many thanks to Sylvinus

**Comment by samyakbhuta** [comment]
Thanks @sylvinus ,

Manual copying does solve the issue. Watch out your python version, though, before you fire the below command from your `cordova` direcotry.

```
sudo cp -R ../Cordova/recipes /Library/Python/2.7/site-packages/cordova-0.1.0-py2.7.egg/
```

```
sudo cp -R ../Cordova/generate-template /Library/Python/2.7/site-packages/cordova-0.1.0-py2.7.egg/
```
